name = "sports-proxy"
main = "src/index.js"
compatibility_date = "2025-01-06"

# KV for edge caching
[[kv_namespaces]]
binding = "SPORTS_CACHE"
id = "f99c4a83cc5948d6979ac2efd7d7c7a8"
preview_id = "71977fcf6ac442c6bba1ea85d7a6d6d8"

# R2 for cold storage
[[r2_buckets]]
binding = "SPORTS_STORAGE"
bucket_name = "sports-data-bucket"

# Durable Objects for rate limiting and coordination
[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

# Durable Object migrations (SQLite for free plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]

# Service Bindings - zero-latency worker-to-worker communication
[[services]]
binding = "MLB_MCP"
service = "baseball-stats-mcp"

[[services]]
binding = "HOCKEY_MCP"
service = "hockey-stats-mcp"

# Will add ESPN when ready
# [[services]]
# binding = "ESPN_MCP"  
# service = "espn-mcp"

# Environment variables
[vars]
CACHE_TTL_HOT = "10"
CACHE_TTL_COLD = "300"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }